### PR TITLE
Changed simplifyMatrix()

### PR DESCRIPTION
**Pull request by jtMUMT**
Only empty edge-rows and edge-columns will be pruned by simplifyMatrix(). This is to make it easier to compose larger form layouts and give a bit more control to the user.

Context: I'm making a database for my small business and I was frustrated by the aggressive pruning of the form matrix columns/rows which was making it difficult to arrange the (many) widgets. Changing the pruning behaviour to only target the edges means that I can break up clusters of widgets with empty space, and I can make more working space while I experiment with the layout.

Love the software, and happy to contribute. If this change goes against your desired usage I understand completely, no bad feels.

### CODE REVIEW

**Comment by joshirio** [comment]
Nice addition, I'll do some tests and if everything works we can merge it for the 2.6 release. Thank you for the contribution!

**Comment by jtMUMT** [comment]
My pleasure—I hope it doesn't break everything!

**Comment by joshirio** [comment]
I'm merging your work as an additional feature but leaving the current behavior as default.
I'll add a new option in the settings to allow empty rows/columns in the form view for users wishing more layout freedom.

Thanks! And of course I'll add you to the contributors list.

**Comment by jtMUMT** [comment]
Happy to contribute :)

**Comment by joshirio** [comment]
Actually I think I'll make this the new default because removing free space is easy for the user, they just move a couple of widgets instead of hunting down unknown settings... Anyway an option will be provided in the settings.

**Pull request merged**
